### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by ebarthur** [rkowusu17/Portfolio#1]
Since you're comfortable with CSS, I'd assume you know media queries.

If you will, apply media queries to your code to enable responsive web design by allowing the adaptation of your webpage’s appearance to different devices and screen sizes.

In that case, if I open your page on my phone or iPad, it'll look good and not messed up.

**Comment by rkowusu17** [comment]
Thank you very much for this advice. Now I can say I'm comfortable with that too and tailwind Css. I'm starting JS afresh and I hope it'll be really smooth this time

**Comment by ebarthur** [comment]
You're welcome brother!
